baseURL: 'https://magnusborresen.com'
languageCode: en-us
title: Magnus Borresen
theme: archie
copyright: © Magnus Borresen
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
params:
  mode: auto
  useCDN: true
  katex: true
  subtitle: 'Personal blog and vomitting about the weird projects I do'
  favicon: '/static/assets/img/favicon.ico'
  social:
    - name: GitHub
      icon: github
      url: 'https://github.com/athul/magborresen'
    - name: LinkedIn
      icon: linkedin
      url: 'https://www.linkedin.com/in/mag-borresen/'

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /posts/
      weight: 2
    - name: Projects
      url: /projects/
      weight: 3
    - name: Other Stuff
      url: /IFIL/
      weight: 4