baseURL: https://magnusborresen.com
disablePathToLower: true
languageCode: en-us
title: Magnus Borresen
theme: "hugo-theme-console-mb"

params:
  titleCutting: true
  animateStyle: animated zoomIn fast
  navlinks:
    - name: about/
      url: about/
    - name: posts/
      url: posts/
    - name: projects/
      url: projects/

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4